### ISSUE TITLE
Implementing Google Signup

### ISSUE THREAD

**Issue by charithhewage** [alexanmtz/truppie#13]
User authentication section has been developed on top of [Devise](https://github.com/plataformatec/devise) and Omniauth. Hence, we can easily implement google signup with truppie. (As my experience, most of the users do not like to use LinkedIn for their social logins.) As well as, Implementing multiple options to signup workflows will reduce the usability and the user experience. 
<img width="256" alt="multiple social logins" src="https://cloud.githubusercontent.com/assets/6915496/25519184/2cbe8ff4-2c3a-11e7-8e36-67c327fd169d.png"><img width="256" alt="multiple social logins" src="https://cloud.githubusercontent.com/assets/6915496/25519202/3a4ba922-2c3a-11e7-880a-7c743f0048c2.jpg">

**Comment by alexanmtz** [comment]
Thanks @charithhewage for the feedback. Actually in the website we are using login with Facebook that is enough for now, because is our main user choice of login. Maybe we support other ones in the future.

![pageshot of truppie 2017-04-05-1456 42](https://cloud.githubusercontent.com/assets/88840/25529605/2126a562-2c23-11e7-9171-8fe9e703671c.png)
.
