### ISSUE TITLE
Contribution guidelines for a basic text document change

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#7]
A basic guideline contribution document in CONTRIBUTING.md to make changes in documentation and translation.

### Steps:
* Fork the project
* Edit CONTRIBUTING.md with the guidelines (the guideline is what you've done for create this guideline) creating a section "Basic document change" with a header level 2
* Create a Pull request refering this issue with #7
* Wait for review

PS. You need to upload images to reference it in the project. You can ask me @alexanmtz to upload the image for you and send a remote link to be used in the contribution guidelines for the print of the steps to contribute. Or you can upload files commenting the issue and get the url to use in documentation.

This is the guideline that needs to be edited:

<img width="1011" alt="The contribution guideline" src="https://cloud.githubusercontent.com/assets/88840/25234472/6c9152be-25e2-11e7-9965-e57ba758be2a.png">

### Why this is important?
As a collaborative platform we need the contribution guidelines for beginners be able to know how to contribute with this project. This document will be always visible when creating a new issue or open a pull request.

**Comment by mthais** [comment]
_Fork is a resource that allows the user to have a copy of a project. The project can have new ramifications after being approved by the admin._ 

**Steps to fork a Project:**

* Click on button “Fork”
* The system displays the following screen so that the user can choose a repository to save a project
 
![Fork](https://cloud.githubusercontent.com/assets/27444220/25282917/56b5111e-2688-11e7-9b5e-831d3a5e760d.PNG)

After the repository was chosen, the system displays all the project files then the user can chose requested file to edit and click on the file to open project files.

![s_a](https://cloud.githubusercontent.com/assets/27444220/25283075/ebd3ffb2-2688-11e7-88f6-3f2a383dd871.PNG)
 
The user has to click on the icon below to edit the project files.

![edit_](https://cloud.githubusercontent.com/assets/27444220/25283203/5af29d68-2689-11e7-8360-83f3e9e61d3a.PNG)

The system allows the user to edit the file, this way the user can improve and correct mistakes as desired.

After performing changes, the user must fill in the form “Propose file change”, explain the changes performed in the comment box and click on the button “Propose file change”.
 
![sp](https://cloud.githubusercontent.com/assets/27444220/25283368/e32c4544-2689-11e7-9f5c-c0de74bad581.PNG)
![pf](https://cloud.githubusercontent.com/assets/27444220/25283453/34256ade-268a-11e7-939b-7fd632533b64.PNG)

 
The system displays the screen "Comparing Changes" comparing the codes. Then the user has to click on the button "Create a pull request".

![comparing](https://cloud.githubusercontent.com/assets/27444220/25283584/a5ae2290-268a-11e7-9d03-321f1e066dc6.PNG)


_Pull Request allows others users to see the changes that were performed in Github repository. When a pull request is opened, the system allows others users to discuss a topic and analyze a request. Other developers can collaborate with the user’s projects in Github repository._

**Steps to Open a Pull Request:**
* Fill in the form with the user's technical comment on future changes
* Upload the bug image that was found or upload the image/file that shows the improvement
* Click on button “Create pull request”

 
![pull request](https://cloud.githubusercontent.com/assets/27444220/25283612/b9687f60-268a-11e7-843f-ba14d2450d48.PNG)


After the Pull Request being created, the system displays a screen with a request and information about a demand.
 
![text correction](https://cloud.githubusercontent.com/assets/27444220/25283698/fe3ef6f0-268a-11e7-9086-a60388595333.PNG)

After the user has to click on the link below the comment box "Travis" to view the system executing the automated testing integration according to the picture below.

![test](https://cloud.githubusercontent.com/assets/27444220/25283725/180cb568-268b-11e7-85dc-46ee5ea20ad1.PNG)

**Comment by mthais** [comment]
When the system finishes the integration process test, every change has to be approved by the project admin. If the admin doesn't approve a change, the admin can request the review of the changes done in the project. For the user to see the feedback, the user has to click on the link “Pull resquest”, select the tab "Created" then the user has to select the pull request that has the review.

![request review](https://cloud.githubusercontent.com/assets/27444220/25400108/f0931726-29c7-11e7-95e2-f4c14da0b892.PNG)

The system displays the screen with comments about the pull request review on the tab "Conversation" then the user has to click on the tab “Files changes”.

![change pull](https://cloud.githubusercontent.com/assets/27444220/25400174/206be14e-29c8-11e7-939c-4a08dcdfb4fb.PNG)

The system displays the project edition screen. The user has to click on the icon below to edit the project files.

![edit](https://cloud.githubusercontent.com/assets/27444220/25400216/494da598-29c8-11e7-9316-626d3aa38ff3.PNG)

The system allows the user to edit the file, this way the user can fix errors as suggested by admin. 
After performing changes, the user must fill in the form “Commit changes”, explain the changes performed in the comment box, select the option “Commit directly to the patch-3 branch” and click on the button “Commit changes”.

![edicao do arquivo](https://cloud.githubusercontent.com/assets/27444220/25400309/7dd3ddfa-29c8-11e7-8a39-bf156529e48a.PNG)
![commit c](https://cloud.githubusercontent.com/assets/27444220/25400345/9e70da36-29c8-11e7-987b-0fc72211cf40.PNG)

After the user commit the project, the project admin has to approve again, to the project can be intregated with original project.

**Comment by alexanmtz** [comment]
As the #9 the guide was created and merged
